# Data Cleaning

### Library Import

In [70]:
import pandas as pd
import numpy as np

### Import Dataset

In [71]:
df=pd.read_csv("C:\\Users\\KIIT\\GFG_project\\data\\traffic_dataset.csv",encoding='latin1')

In [72]:
df.head()

,Timestamp,IR Presence (Lane 1-4),Vehicle Count,Avg Speed (km/h),Vehicle Types Detected,Vehicle Density (%),Saturation Flow Rate(veh/hr/lane),Volume to\n Saturation Lane Traffic ratio(%),FreeFlowSpeed (km/h),TSR,VLSR,Speed Factor,CI,Congestion Level
0,8:00:00,"[0, 0, 1, 0]",97,31.2,"10 Bikes, 90 Ambulance, 60 Fire Extinguisher",40,1800,1.347222,50,0.376,0.013472,0.624,0.240589,Moderate
1,8:01:00,"[0, 0, 1, 1]",126,48.5,"32 Ambulance, 94 Ambulance",57,1800,1.750000,50,0.030,0.017500,0.970,0.241000,Moderate
2,8:02:00,"[1, 0, 0, 0]",61,42.0,"99 Trucks, 76 Patrol, 65 Fire Extinguisher",82,1800,0.847222,50,0.160,0.008472,0.840,0.363389,High
3,8:03:00,"[0, 0, 0, 0]",170,38.0,"50 Cars, 71 Patrol, 63 Fire Extinguisher",75,1800,2.361111,50,0.240,0.023611,0.760,0.357444,High
4,8:04:00,"[1, 0, 0, 0]",180,24.7,"17 Patrol, 93 Cars, 25 Bikes, 23 Vans",90,1800,2.500000,50,0.506,0.025000,0.494,0.471200,Very High

In [73]:
print("Number of rows and columns:", df.shape)
df.head()

Number of rows and columns: (4354, 14)

,Timestamp,IR Presence (Lane 1-4),Vehicle Count,Avg Speed (km/h),Vehicle Types Detected,Vehicle Density (%),Saturation Flow Rate(veh/hr/lane),Volume to\n Saturation Lane Traffic ratio(%),FreeFlowSpeed (km/h),TSR,VLSR,Speed Factor,CI,Congestion Level
0,8:00:00,"[0, 0, 1, 0]",97,31.2,"10 Bikes, 90 Ambulance, 60 Fire Extinguisher",40,1800,1.347222,50,0.376,0.013472,0.624,0.240589,Moderate
1,8:01:00,"[0, 0, 1, 1]",126,48.5,"32 Ambulance, 94 Ambulance",57,1800,1.750000,50,0.030,0.017500,0.970,0.241000,Moderate
2,8:02:00,"[1, 0, 0, 0]",61,42.0,"99 Trucks, 76 Patrol, 65 Fire Extinguisher",82,1800,0.847222,50,0.160,0.008472,0.840,0.363389,High
3,8:03:00,"[0, 0, 0, 0]",170,38.0,"50 Cars, 71 Patrol, 63 Fire Extinguisher",75,1800,2.361111,50,0.240,0.023611,0.760,0.357444,High
4,8:04:00,"[1, 0, 0, 0]",180,24.7,"17 Patrol, 93 Cars, 25 Bikes, 23 Vans",90,1800,2.500000,50,0.506,0.025000,0.494,0.471200,Very High

In [74]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 4354 entries, 0 to 4353
Data columns (total 14 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Timestamp                                    4354 non-null   str
 1   IR Presence (Lane 1-4)                       4354 non-null   str
 2   Vehicle Count                                4354 non-null   int64
 3   Avg Speed (km/h)                             4354 non-null   float64
 4   Vehicle Types Detected                       4354 non-null   str
 5   Vehicle Density (%)                          4354 non-null   int64
 6   Saturation Flow Rate(veh/hr/lane)            4354 non-null   int64
 7   Volume to
 Saturation Lane Traffic ratio(%)  4354 non-null   float64
 8   FreeFlowSpeed (km/h)                         4354 non-null   int64
 9   TSR                                          4354 non-null   float64
 10  VLSR                                         4354 non-null   float64
 11  Speed Factor                                 4354 non-null   float64
 12  CI                                           4354 non-null   float64
 13  Congestion Level                             4354 non-null   str
dtypes: float64(6), int64(4), str(4)
memory usage: 476.3 KB
None

In [75]:
print(df.isnull().sum())

Timestamp                                       0
IR Presence (Lane 1-4)                          0
Vehicle Count                                   0
Avg Speed (km/h)                                0
Vehicle Types Detected                          0
Vehicle Density (%)                             0
Saturation Flow Rate(veh/hr/lane)               0
Volume to\n Saturation Lane Traffic ratio(%)    0
FreeFlowSpeed (km/h)                            0
TSR                                             0
VLSR                                            0
Speed Factor                                    0
CI                                              0
Congestion Level                                0
dtype: int64

In [76]:
print("Duplicate rows:", df.duplicated().sum())
 
df = df.drop_duplicates()

Duplicate rows: 0

In [77]:
df.columns = df.columns.str.replace("\n", " ")
df.columns = df.columns.str.strip()
 
print(df.columns.tolist())

['Timestamp', 'IR Presence (Lane 1-4)', 'Vehicle Count', 'Avg Speed (km/h)', 'Vehicle Types Detected', 'Vehicle Density (%)', 'Saturation Flow Rate(veh/hr/lane)', 'Volume to  Saturation Lane Traffic ratio(%)', 'FreeFlowSpeed (km/h)', 'TSR', 'VLSR', 'Speed Factor', 'CI', 'Congestion Level']

In [78]:
df["Hour"] = df["Timestamp"].str.split(":").str[0].astype(int)

In [79]:
df["Hour"] = df["Hour"] % 24
 
print(df[["Timestamp", "Hour"]].head())

  Timestamp  Hour
0   8:00:00     8
1   8:01:00     8
2   8:02:00     8
3   8:03:00     8
4   8:04:00     8

"AI"  "ai" "Ai"

In [80]:
df["Vehicle Count"] = pd.to_numeric(df["Vehicle Count"], errors="coerce")
df["Avg Speed (km/h)"] = pd.to_numeric(df["Avg Speed (km/h)"], errors="coerce")
df["Vehicle Density (%)"] = pd.to_numeric(df["Vehicle Density (%)"], errors="coerce")

In [81]:
df["Vehicle Count"] = df["Vehicle Count"].fillna(df["Vehicle Count"].median())
df["Avg Speed (km/h)"] = df["Avg Speed (km/h)"].fillna(df["Avg Speed (km/h)"].median())
df["Vehicle Density (%)"] = df["Vehicle Density (%)"].fillna(df["Vehicle Density (%)"].median())

In [82]:
df["Previous_Traffic"] = df["Vehicle Count"].shift(1)

df["Previous_Traffic"] = df["Previous_Traffic"].bfill()

In [83]:
print(df["Congestion Level"].unique())
print(df["Congestion Level"].value_counts())

<StringArray>
['Moderate', 'High', 'Very High', 'Low']
Length: 4, dtype: str
Congestion Level
High         1686
Moderate     1642
Very High     592
Low           434
Name: count, dtype: int64

In [84]:
df_simple = df.drop(columns=["IR Presence (Lane 1-4)", "Vehicle Types Detected"])

In [85]:
print("Final shape:", df_simple.shape)
print(df_simple.isnull().sum())   # should all be 0 now
print(df_simple.head())

Final shape: (4354, 14)
Timestamp                                      0
Vehicle Count                                  0
Avg Speed (km/h)                               0
Vehicle Density (%)                            0
Saturation Flow Rate(veh/hr/lane)              0
Volume to  Saturation Lane Traffic ratio(%)    0
FreeFlowSpeed (km/h)                           0
TSR                                            0
VLSR                                           0
Speed Factor                                   0
CI                                             0
Congestion Level                               0
Hour                                           0
Previous_Traffic                               0
dtype: int64
  Timestamp  Vehicle Count  Avg Speed (km/h)  Vehicle Density (%)  \
0   8:00:00             97              31.2                   40
1   8:01:00            126              48.5                   57
2   8:02:00             61              42.0                   82
3   8:03:00            170              38.0                   75
4   8:04:00            180              24.7                   90

   Saturation Flow Rate(veh/hr/lane)  \
0                               1800
1                               1800
2                               1800
3                               1800
4                               1800

   Volume to  Saturation Lane Traffic ratio(%)  FreeFlowSpeed (km/h)    TSR  \
0                                     1.347222                    50  0.376
1                                     1.750000                    50  0.030
2                                     0.847222                    50  0.160
3                                     2.361111                    50  0.240
4                                     2.500000                    50  0.506

       VLSR  Speed Factor        CI Congestion Level  Hour  Previous_Traffic
0  0.013472         0.624  0.240589         Moderate     8              97.0
1  0.017500         0.970  0.241000         Moderate     8              97.0
2  0.008472         0.840  0.363389             High     8             126.0
3  0.023611         0.760  0.357444             High     8              61.0
4  0.025000         0.494  0.471200        Very High     8             170.0

In [86]:
df_simple.to_csv(r"C:\Users\KIIT\GFG_project\data\traffic_dataset_clean.csv", index=False)
print("Saved as traffic_dataset_clean.csv")

Saved as traffic_dataset_clean.csv

In [87]:
df=pd.read_csv("C:\\Users\\KIIT\\GFG_project\\data\\traffic_dataset_clean.csv",encoding='latin1')

In [88]:
df.head()

,Timestamp,Vehicle Count,Avg Speed (km/h),Vehicle Density (%),Saturation Flow Rate(veh/hr/lane),Volume to Saturation Lane Traffic ratio(%),FreeFlowSpeed (km/h),TSR,VLSR,Speed Factor,CI,Congestion Level,Hour,Previous_Traffic
0,8:00:00,97,31.2,40,1800,1.347222,50,0.376,0.013472,0.624,0.240589,Moderate,8,97.0
1,8:01:00,126,48.5,57,1800,1.750000,50,0.030,0.017500,0.970,0.241000,Moderate,8,97.0
2,8:02:00,61,42.0,82,1800,0.847222,50,0.160,0.008472,0.840,0.363389,High,8,126.0
3,8:03:00,170,38.0,75,1800,2.361111,50,0.240,0.023611,0.760,0.357444,High,8,61.0
4,8:04:00,180,24.7,90,1800,2.500000,50,0.506,0.025000,0.494,0.471200,Very High,8,170.0