In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r"C:\Users\KIIT\OneDrive\urban_traffic\data\raw\traffic_dataset.csv")

In [3]:
(data['Avg Speed (km/h)']>50).sum()

np.int64(0)

In [4]:
data['Congestion Level'].unique()

<StringArray>
['Moderate', 'High', 'Very High', 'Low']
Length: 4, dtype: str

In [5]:
data.dtypes

Timestamp                                           str
IR Presence (Lane 1-4)                              str
Vehicle Count                                     int64
Avg Speed (km/h)                                float64
Vehicle Types Detected                              str
Vehicle Density (%)                               int64
Saturation Flow Rate(veh/hr/lane)                 int64
Volume to\n Saturation Lane Traffic ratio(%)    float64
FreeFlowSpeed (km/h)                              int64
TSR                                             float64
VLSR                                            float64
Speed Factor                                    float64
CI                                              float64
Congestion Level                                    str
dtype: object

In [6]:
print((data["Timestamp"] == "24:00:00").sum())

1

In [7]:
(data['Timestamp']>"24:00:00").sum()

np.int64(3513)

In [8]:
(data['Timestamp']>"24:00:00").sum()

np.int64(3513)

In [9]:
(data['Avg Speed (km/h)']<0).sum()

np.int64(0)

In [10]:
(data['Vehicle Count']<0).sum()

np.int64(0)

In [11]:
(data['Vehicle Density (%)']<0).sum()

np.int64(0)

In [12]:
data.shape

(4354, 14)

In [13]:
(data['CI']<0).sum()

np.int64(0)

In [14]:
numeric_columns = data.select_dtypes(include="number").columns

print(numeric_columns)

Index(['Vehicle Count', 'Avg Speed (km/h)', 'Vehicle Density (%)',
       'Saturation Flow Rate(veh/hr/lane)',
       'Volume to\n Saturation Lane Traffic ratio(%)', 'FreeFlowSpeed (km/h)',
       'TSR', 'VLSR', 'Speed Factor', 'CI'],
      dtype='str')

In [15]:
data[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
Vehicle Count,4354.0,125.081994,43.230983,50.000000,88.000000,125.000000,162.000000,200.000000
Avg Speed (km/h),4354.0,34.926757,8.692768,20.000000,27.400000,35.050000,42.400000,50.000000
Vehicle Density (%),4354.0,59.796279,17.800153,30.000000,44.000000,60.000000,75.000000,90.000000
Saturation Flow Rate(veh/hr/lane),4354.0,1800.000000,0.000000,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000
Volume to\n Saturation Lane Traffic ratio(%),4354.0,1.737250,0.600430,0.694444,1.222222,1.736111,2.250000,2.777778
FreeFlowSpeed (km/h),4354.0,50.000000,0.000000,50.000000,50.000000,50.000000,50.000000,50.000000
TSR,4354.0,0.301465,0.173855,0.000000,0.152000,0.299000,0.452000,0.600000
VLSR,4354.0,0.017372,0.006004,0.006944,0.012222,0.017361,0.022500,0.027778
Speed Factor,4354.0,0.698535,0.173855,0.400000,0.548000,0.701000,0.848000,1.000000
CI,4354.0,0.306427,0.079303,0.123689,0.244708,0.305628,0.366706,0.487511

In [16]:
data['Timestamp'].duplicated().sum()

np.int64(0)

In [17]:
data.to_csv(r'C:\Users\KIIT\OneDrive\urban_traffic\data\cleaned\cleaned_traffic.csv')

In [18]:
data["Timestamp"] = data["Timestamp"].astype(str)

In [19]:
data["Timestamp"] = data["Timestamp"].replace(
    "24:00:00",
    "00:00:00"
)

In [20]:
data.columns

Index(['Timestamp', 'IR Presence (Lane 1-4)', 'Vehicle Count',
       'Avg Speed (km/h)', 'Vehicle Types Detected', 'Vehicle Density (%)',
       'Saturation Flow Rate(veh/hr/lane)',
       'Volume to\n Saturation Lane Traffic ratio(%)', 'FreeFlowSpeed (km/h)',
       'TSR', 'VLSR', 'Speed Factor', 'CI', 'Congestion Level'],
      dtype='str')

In [21]:
data['Timestamp'].tail(20)

4334    80:14:00
4335    80:15:00
4336    80:16:00
4337    80:17:00
4338    80:18:00
4339    80:19:00
4340    80:20:00
4341    80:21:00
4342    80:22:00
4343    80:23:00
4344    80:24:00
4345    80:25:00
4346    80:26:00
4347    80:27:00
4348    80:28:00
4349    80:29:00
4350    80:30:00
4351    80:31:00
4352    80:32:00
4353    80:33:00
Name: Timestamp, dtype: str

In [22]:
data["Timestamp"] = pd.to_timedelta(data["Timestamp"])

In [23]:

print(data["Timestamp"].dtype)

timedelta64[us]

In [24]:
data.shape

(4354, 14)

In [25]:
data.columns

Index(['Timestamp', 'IR Presence (Lane 1-4)', 'Vehicle Count',
       'Avg Speed (km/h)', 'Vehicle Types Detected', 'Vehicle Density (%)',
       'Saturation Flow Rate(veh/hr/lane)',
       'Volume to\n Saturation Lane Traffic ratio(%)', 'FreeFlowSpeed (km/h)',
       'TSR', 'VLSR', 'Speed Factor', 'CI', 'Congestion Level'],
      dtype='str')

In [26]:
data['Timestamp'] = pd.to_timedelta(data['Timestamp'])

In [27]:
data['Timestamp'].tail()

4349   3 days 08:29:00
4350   3 days 08:30:00
4351   3 days 08:31:00
4352   3 days 08:32:00
4353   3 days 08:33:00
Name: Timestamp, dtype: timedelta64[us]

In [28]:
data['Timestamp'] = pd.to_timedelta(data['Timestamp'])

In [29]:
data['Timestamp'].head()

0   0 days 08:00:00
1   0 days 08:01:00
2   0 days 08:02:00
3   0 days 08:03:00
4   0 days 08:04:00
Name: Timestamp, dtype: timedelta64[us]

In [30]:
data['Hour'] = (data['Timestamp'].dt.total_seconds() // 3600).astype(int)

In [31]:
data['Timestamp'].tail()

4349   3 days 08:29:00
4350   3 days 08:30:00
4351   3 days 08:31:00
4352   3 days 08:32:00
4353   3 days 08:33:00
Name: Timestamp, dtype: timedelta64[us]

In [32]:
print(data['Timestamp'].dtype)

timedelta64[us]

In [33]:
data['Timestamp'] = data['Timestamp'].astype('timedelta64[ns]')

In [34]:
print(data['Timestamp'].dtype)

timedelta64[ns]

In [35]:
data['Hour'] = ((data['Timestamp'].dt.total_seconds() // 3600) % 24).astype(int)

In [36]:
print(data['Hour'])

0       8
1       8
2       8
3       8
4       8
       ..
4349    8
4350    8
4351    8
4352    8
4353    8
Name: Hour, Length: 4354, dtype: int64

In [37]:
data['Hour'].head()

0    8
1    8
2    8
3    8
4    8
Name: Hour, dtype: int64

In [38]:
data.to_csv(r'C:\Users\KIIT\OneDrive\urban_traffic\data\cleaned\cleaned_traffic2.csv')

In [39]:
data1 = pd.read_csv(r'C:\Users\KIIT\OneDrive\urban_traffic\data\cleaned\cleaned_traffic2.csv')

In [40]:
data1.head()

,Unnamed: 0,Timestamp,IR Presence (Lane 1-4),Vehicle Count,Avg Speed (km/h),Vehicle Types Detected,Vehicle Density (%),Saturation Flow Rate(veh/hr/lane),Volume to\n Saturation Lane Traffic ratio(%),FreeFlowSpeed (km/h),TSR,VLSR,Speed Factor,CI,Congestion Level,Hour
0,0,0 days 08:00:00,"[0, 0, 1, 0]",97,31.2,"10 Bikes, 90 Ambulance, 60 Fire Extinguisher",40,1800,1.347222,50,0.376,0.013472,0.624,0.240589,Moderate,8
1,1,0 days 08:01:00,"[0, 0, 1, 1]",126,48.5,"32 Ambulance, 94 Ambulance",57,1800,1.750000,50,0.030,0.017500,0.970,0.241000,Moderate,8
2,2,0 days 08:02:00,"[1, 0, 0, 0]",61,42.0,"99 Trucks, 76 Patrol, 65 Fire Extinguisher",82,1800,0.847222,50,0.160,0.008472,0.840,0.363389,High,8
3,3,0 days 08:03:00,"[0, 0, 0, 0]",170,38.0,"50 Cars, 71 Patrol, 63 Fire Extinguisher",75,1800,2.361111,50,0.240,0.023611,0.760,0.357444,High,8
4,4,0 days 08:04:00,"[1, 0, 0, 0]",180,24.7,"17 Patrol, 93 Cars, 25 Bikes, 23 Vans",90,1800,2.500000,50,0.506,0.025000,0.494,0.471200,Very High,8

In [41]:
data1.iloc[300:4440, 15]

300     13
301     13
302     13
303     13
304     13
        ..
4349     8
4350     8
4351     8
4352     8
4353     8
Name: Hour, Length: 4054, dtype: int64

In [42]:
data2 = pd.read_csv(r'C:\Users\KIIT\OneDrive\urban_traffic\data\cleaned\cleaned_traffic2.csv')

In [43]:
data2.head(20)

,Unnamed: 0,Timestamp,IR Presence (Lane 1-4),Vehicle Count,Avg Speed (km/h),Vehicle Types Detected,Vehicle Density (%),Saturation Flow Rate(veh/hr/lane),Volume to\n Saturation Lane Traffic ratio(%),FreeFlowSpeed (km/h),TSR,VLSR,Speed Factor,CI,Congestion Level,Hour
0,0,0 days 08:00:00,"[0, 0, 1, 0]",97,31.2,"10 Bikes, 90 Ambulance, 60 Fire Extinguisher",40,1800,1.347222,50,0.376,0.013472,0.624,0.240589,Moderate,8
1,1,0 days 08:01:00,"[0, 0, 1, 1]",126,48.5,"32 Ambulance, 94 Ambulance",57,1800,1.750000,50,0.030,0.017500,0.970,0.241000,Moderate,8
2,2,0 days 08:02:00,"[1, 0, 0, 0]",61,42.0,"99 Trucks, 76 Patrol, 65 Fire Extinguisher",82,1800,0.847222,50,0.160,0.008472,0.840,0.363389,High,8
3,3,0 days 08:03:00,"[0, 0, 0, 0]",170,38.0,"50 Cars, 71 Patrol, 63 Fire Extinguisher",75,1800,2.361111,50,0.240,0.023611,0.760,0.357444,High,8
4,4,0 days 08:04:00,"[1, 0, 0, 0]",180,24.7,"17 Patrol, 93 Cars, 25 Bikes, 23 Vans",90,1800,2.500000,50,0.506,0.025000,0.494,0.471200,Very High,8
5,5,0 days 08:05:00,"[1, 1, 0, 1]",159,24.7,"16 Cars, 34 Cars, 55 Ambulance",30,1800,2.208333,50,0.506,0.022083,0.494,0.230033,Moderate,8
6,6,0 days 08:06:00,"[0, 0, 1, 0]",175,21.7,"28 Fire Extinguisher, 57 Cars, 88 Ambulance, 1...",89,1800,2.430556,50,0.566,0.024306,0.434,0.478922,Very High,8
7,7,0 days 08:07:00,"[1, 0, 0, 1]",145,46.0,"97 Vans, 69 Cars, 30 Trucks, 90 Vans",73,1800,2.013889,50,0.080,0.020139,0.920,0.316056,High,8
8,8,0 days 08:08:00,"[0, 1, 1, 1]",79,38.0,"91 Trucks, 13 Ambulance, 88 Ambulance",43,1800,1.097222,50,0.240,0.010972,0.760,0.224389,Moderate,8
9,9,0 days 08:09:00,"[0, 1, 0, 1]",93,41.2,"38 Trucks, 62 Vans, 79 Ambulance",59,1800,1.291667,50,0.176,0.012917,0.824,0.276367,Moderate,8
10,10,0 days 08:10:00,"[1, 0, 0, 1]",145,20.6,"78 Fire Extinguisher, 22 Vans",43,1800,2.013889,50,0.588,0.020139,0.412,0.297656,Moderate,8
11,11,0 days 08:11:00,"[1, 0, 1, 0]",163,49.1,"82 Vans, 27 Bikes, 91 Fire Extinguisher, 83 Vans",31,1800,2.263889,50,0.018,0.022639,0.982,0.136656,Low,8
12,12,0 days 08:12:00,"[1, 0, 1, 0]",62,45.0,"49 Patrol, 97 Fire Extinguisher",47,1800,0.861111,50,0.100,0.008611,0.900,0.211444,Moderate,8
13,13,0 days 08:13:00,"[1, 0, 0, 0]",169,26.4,"35 Vans, 47 Ambulance, 46 Fire Extinguisher",59,1800,2.347222,50,0.472,0.023472,0.528,0.339789,High,8
14,14,0 days 08:14:00,"[1, 1, 0, 0]",118,25.5,"90 Ambulance, 52 Fire Extinguisher",71,1800,1.638889,50,0.490,0.016389,0.510,0.388556,High,8
15,15,0 days 08:15:00,"[1, 1, 0, 1]",51,25.5,"15 Vans, 68 Patrol",45,1800,0.708333,50,0.490,0.007083,0.510,0.280833,Moderate,8
16,16,0 days 08:16:00,"[0, 1, 1, 1]",80,29.1,"89 Fire Extinguisher, 43 Vans",33,1800,1.111111,50,0.418,0.011111,0.582,0.220044,Moderate,8
17,17,0 days 08:17:00,"[0, 1, 1, 1]",72,35.7,"76 Bikes, 81 Ambulance",67,1800,1.000000,50,0.286,0.010000,0.714,0.329200,High,8
18,18,0 days 08:18:00,"[0, 0, 1, 1]",122,33.0,"40 Vans, 83 Patrol, 73 Patrol",65,1800,1.694444,50,0.340,0.016944,0.660,0.334778,High,8
19,19,0 days 08:19:00,"[0, 0, 0, 1]",120,28.7,"70 Trucks, 57 Trucks, 75 Vans",43,1800,1.666667,50,0.426,0.016667,0.574,0.263867,Moderate,8